import Head from "next/head";
import { getTableById, getTableList } from "@/lib/microcms";

import { GetServerSideProps, NextPage } from "next";
import { BaseMicroCMSApiSingleDataType, SateiPageDataType } from "@/types";

import parser, { domToReact } from "html-react-parser";

type PropsType = {
  data: BaseMicroCMSApiSingleDataType<SateiPageDataType>;
};

const Home: NextPage<PropsType> = ({ data }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <h1 className="bg-red-300">{data.title}</h1>
        <h2>更新日: {data.updatedAt}</h2>
        {data.repeatTable &&
          data.repeatTable.map((content, index) => (
            <div key={index}>
              <b>repeatTableエリア</b>
              <div>{parser(content.table)}</div>
            </div>
          ))}
      </main>
    </>
  );
};
export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const data = await getTableById("ik9hciusz");
  return { props: { data } };
};
