import { GetStaticPaths, GetStaticProps, NextPageContext } from "next";
import Head from "next/head";

export default function Satei({ isPreviewMode, content }) {

  if (!content) {
    return <p>エラーページ</p>
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Next12</h1>
        <div>{JSON.stringify(`isPreviewMode: ${isPreviewMode}`)}</div>
        <div>{isPreviewMode ? "プレビューモード": "Nonプレビュー"}</div>
        <div>{JSON.stringify(content)}</div>
      </main>
    </>
  );
}
// http://localhost:3000/api/preview?slug=/preview/satei/hoge&draftKey=MufKKRnw-f
export const getStaticProps: GetStaticProps = async (context) => {
  const slug = context.params?.slug
  const draftKey = context.previewData?.draftKey
  const isPreviewMode = context.preview
  const content = await fetch(
    `https://${
      process.env.NEXT_PUBLIC_MICROCMS_SERVICE_DOMAIN
    }.microcms.io/api/v1/tables/${slug}/${
      draftKey !== undefined ? `?draftKey=${draftKey}` : ""
    }`,
    { headers: { "X-MICROCMS-API-KEY": process.env.NEXT_PUBLIC_MICROCMS_API_KEY || "" } }
  ).then((res) => res.json());

  return {
    props: {
      isPreviewMode,
      content,
    },
  };
};

export const getStaticPaths: GetStaticPaths = async (req) => {
  let paramList = []
  const contents = await fetch(
    `https://${
      process.env.NEXT_PUBLIC_MICROCMS_SERVICE_DOMAIN
    }.microcms.io/api/v1/tables`,
    { headers: { "X-MICROCMS-API-KEY": process.env.NEXT_PUBLIC_MICROCMS_API_KEY || "" } }
  ).then((res) => res.json());

    for (const item of contents.contents){
      paramList.push({
        params: {
          slug: item.id
        }
      })
    }

  return {
    paths: [...paramList],
    fallback: false
  }
}
