import { GetServerSideProps, GetStaticPaths } from "next";
import Head from "next/head";

export default function Shaken({ isPreviewMode, content }) {

  if (!content) {
    return <p>エラーページ</p>
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>shakenディレクトリ(SSR)</h1>
        <div>{JSON.stringify(`isPreviewMode: ${isPreviewMode}`)}</div>
        <div>{isPreviewMode ? "プレビューモード": "Nonプレビュー"}</div>
        <div>{JSON.stringify(content)}</div>
      </main>
    </>
  );
}
// http://localhost:3000/api/preview?slug=/preview/satei/hoge&draftKey=MufKKRnw-f
export const getServerSideProps: GetServerSideProps = async (context) => {
  const slug = context.params?.slug
  const draftKey = context.previewData?.draftKey
  const isPreviewMode = context.preview
  const content = await fetch(
    `https://${
      process.env.NEXT_PUBLIC_MICROCMS_SERVICE_DOMAIN
    }.microcms.io/api/v1/tables/${slug}/${
      draftKey !== undefined ? `?draftKey=${draftKey}` : ""
    }`,
    { headers: { "X-MICROCMS-API-KEY": process.env.NEXT_PUBLIC_MICROCMS_API_KEY || "" } }
  ).then((res) => res.json());

  return {
    props: {
      isPreviewMode,
      content,
    },
  };
};

